name = "ocapn-lean"
version = "0.1.0"
defaultTargets = ["OcapnLean"]

[[require]]
name = "veil"
git = "https://github.com/verse-lab/veil.git"
rev = "main"

[[lean_lib]]
name = "OcapnLean"
globs = ["OcapnLean", "OcapnLean.+"]

[[lean_exe]]
name = "ocapn-server"
root = "OcapnLean.Server"
