#!/usr/bin/env python3
"""Regenerate the Syrup interop fixtures used in
OcapnLean/Test/Interop.lean.

This script runs the upstream Python reference Syrup encoder against
the same set of test values and prints out byte-level fixtures that
should match what our Lean encoder produces.

Run from the project root:

    python3 scripts/regenerate-interop-fixtures.py

It does not modify any file; copy/paste the generated fixtures into
OcapnLean/Test/Interop.lean.
"""
from __future__ import annotations

import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "projects/syrup-ocapn/impls/python"))

import syrup  # noqa: E402

VALUES = [
    ("bool true",         True),
    ("bool false",        False),
    ("int 0",             0),
    ("int 1",             1),
    ("int 42",            42),
    ("int (-7)",          -7),
    ("int 100",           100),
    ("bytes []",          b""),
    ("bytes [0x63, 0x61, 0x74]", b"cat"),
]


def to_lean_bytes(b: bytes) -> str:
    inner = ", ".join(f"0x{x:02x}" for x in b)
    return f"[{inner}]"


def main() -> int:
    print("-- generated by scripts/regenerate-interop-fixtures.py")
    width = max(len(label) for label, _ in VALUES)
    for label, value in VALUES:
        enc = syrup.syrup_encode(value)
        comment = repr(enc.decode("latin-1"))
        print(
            f"example : encode (.{label:<{width}}) "
            f"= {to_lean_bytes(enc)} := by native_decide  -- {comment}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
